# Generated by Django 4.0.4 on 2022-04-16 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(default=datetime.date(2022, 4, 16), verbose_name='Дата')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('number', models.PositiveIntegerField(verbose_name='Количество')),
                ('distance', models.PositiveIntegerField(verbose_name='Расстояние')),
            ],
            options={
                'verbose_name': 'Тестовая таблица',
                'verbose_name_plural': 'Тестовая таблица',
            },
        ),
    ]
