# Generated by Django 4.0.4 on 2022-04-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_testtable_visible_alter_testtable_date_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtable',
            old_name='visible',
            new_name='visible1',
        ),
    ]
