# Generated by Django 4.0.4 on 2022-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_testtable_visible1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtable',
            name='visible1',
        ),
        migrations.AddField(
            model_name='testtable',
            name='visible',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
