# Generated by Django 4.0.4 on 2022-04-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_remove_testtable_visible1_testtable_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='visible',
            field=models.PositiveIntegerField(),
        ),
    ]
