# Generated by Django 4.0.4 on 2022-04-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_testtable_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
